# base image
FROM node:latest

# Create app directory
WORKDIR /usr/src/server

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

COPY keys/example_com.key /usr/src
COPY keys/example_com.csr /usr/src
COPY keys/updullah_me.crt /usr/src

EXPOSE 4000
CMD [ "npm", "start" ]